// Generated by CoffeeScript 1.3.3
(function() {
  var ErrorList;

  ErrorList = (function() {

    function ErrorList() {}

    return ErrorList;

  })();

  module.exports = ErrorList;

}).call(this);
