// Generated by CoffeeScript 1.3.3
(function() {
  var _;

  _ = require('lodash');

  module.exports = {
    isPresent: function(thing) {
      if (_.isNull(thing)) {
        throw new Error('Required');
      }
    },
    isLongerThan: function(length) {
      return function(thing) {
        if (thing && thing.length <= length) {
          throw new Error('Is too short');
        }
      };
    },
    isShorterThan: function(length) {
      return function(thing) {
        if (thing && thing.length >= length) {
          throw new Error('Is too long');
        }
      };
    }
  };

}).call(this);
