// Generated by CoffeeScript 1.3.3
(function() {
  var Array, Type, errors, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  errors = require('../errors');

  Type = require('./type');

  _ = require('lodash');

  Array = (function(_super) {

    __extends(Array, _super);

    function Array() {
      return Array.__super__.constructor.apply(this, arguments);
    }

    Array.prototype["default"] = function() {
      return [];
    };

    Array.prototype.isCorrectType = _.isArray;

    Array.prototype.coerce = function(thing) {
      var stripped;
      if (!_.isString(thing)) {
        throw new errors.ConversionError;
      }
      stripped = thing.replace(/\s+/g, '');
      switch (stripped) {
        case 'true':
          return true;
        case 'false':
          return false;
        default:
          throw new errors.ConversionError;
      }
    };

    Array.prototype.isBlank = function() {
      return this.value.length === 0;
    };

    return Array;

  })(Type);

  module.exports = Array;

}).call(this);
