// Generated by CoffeeScript 1.3.3
(function() {
  var RunwayArray, RunwayType, errors, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  errors = require('./errors');

  RunwayType = require('./type');

  _ = require('lodash');

  RunwayArray = (function(_super) {

    __extends(RunwayArray, _super);

    function RunwayArray() {
      return RunwayArray.__super__.constructor.apply(this, arguments);
    }

    RunwayArray.prototype["default"] = function() {
      return [];
    };

    RunwayArray.prototype.isCorrectType = _.isArray;

    RunwayArray.prototype.coerce = function(thing) {
      if (_.isString(thing) || _.isBoolean(thing) || _.isNumber(thing)) {
        return [thing];
      } else {
        throw new errors.ConversionError;
      }
    };

    RunwayArray.prototype.isBlank = function() {
      return this.value.length === 0;
    };

    return RunwayArray;

  })(RunwayType);

  module.exports = RunwayArray;

}).call(this);
