// Generated by CoffeeScript 1.3.3
(function() {
  var AttributeError, ConversionError,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ConversionError = (function(_super) {

    __extends(ConversionError, _super);

    function ConversionError() {
      this.name = 'ConversionError';
      this.message = 'Invalid type';
    }

    return ConversionError;

  })(Error);

  AttributeError = (function(_super) {

    __extends(AttributeError, _super);

    function AttributeError(attribute) {
      this.name = 'AttributeError';
      this.message = 'Invalid type for attribute ' + attribute;
    }

    return AttributeError;

  })(Error);

  module.exports = {
    ConversionError: ConversionError,
    AttributeError: AttributeError
  };

}).call(this);
