// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    Array: require('./array'),
    Number: require('./number'),
    Boolean: require('./boolean'),
    String: require('./string')
  };

}).call(this);
