// Generated by CoffeeScript 1.3.3
(function() {
  var RunwayString, RunwayType, errors, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  errors = require('./errors');

  RunwayType = require('./type');

  _ = require('lodash');

  RunwayString = (function(_super) {

    __extends(RunwayString, _super);

    function RunwayString() {
      return RunwayString.__super__.constructor.apply(this, arguments);
    }

    RunwayString.prototype["default"] = function() {
      return '';
    };

    RunwayString.prototype.isCorrectType = _.isString;

    RunwayString.prototype.coerce = function(thing) {
      if (_.isNumber(thing) || _.isBoolean(thing) || _.isDate(thing)) {
        return "" + thing;
      } else {
        throw new errors.ConversionError;
      }
    };

    RunwayString.prototype.isBlank = function() {
      return this.value.length === 0;
    };

    return RunwayString;

  })(RunwayType);

  module.exports = RunwayString;

}).call(this);
