// Generated by CoffeeScript 1.3.3
(function() {
  var Type, errors, _;

  _ = require('lodash');

  errors = require('../errors');

  Type = (function() {

    Type.prototype["default"] = function() {
      return null;
    };

    function Type(thing) {
      if (thing == null) {
        thing = null;
      }
      this.set(thing);
      this.changed = false;
    }

    Type.prototype.isCorrectType = function(thing) {
      return false;
    };

    Type.prototype.coerce = function(thing) {
      throw new errors.ConversionError;
    };

    Type.prototype.set = function(thing) {
      if (_.isNull(thing)) {
        this.value = this["default"]();
      } else {
        if (this.isCorrectType(thing)) {
          this.value = thing;
        } else {
          this.value = this.coerce(thing);
        }
      }
      return this.changed = true;
    };

    Type.prototype.isBlank = function() {
      return !this.value;
    };

    return Type;

  })();

  module.exports = Type;

}).call(this);
