// Generated by CoffeeScript 1.3.3
(function() {

  exports.presenceOf = function(attribute) {
    return function(model, next) {
      if (!model[attribute]) {
        model.addError(attribute, "" + attribute + " cannot be blank");
      }
      return next(model);
    };
  };

  exports.formatOf = function(attribute, format) {
    return function(model, next) {
      if (!format.test(model[attribute])) {
        model.addError(attribute, "" + attribute + " is invalid");
      }
      return next(model);
    };
  };

}).call(this);
